package servlet;

import java.io.IOException;

import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import bean.BusinessTripBean;
import dao.ApplicationDAO;
import dao.BusinessTripApplicationDAO;

/**
 * {@code ApplicationDetailServlet} は、申請の詳細情報を表示するための Servlet です。
 * <p>
 * 申請IDから申請種別を取得し、対応するデータ（例：出張費）を読み込み、
 * applicationConfirm.jsp に遷移します。
 * 【Generated by ChatGPT】
 */
@WebServlet("/applicationDetail")
public class ApplicationDetailServlet extends HttpServlet {
	/**
     * GET リクエストを処理し、申請詳細情報の取得・画面遷移を行います。
     * <p>
     * 出張費の場合は {@link BusinessTripBean} をセッション・リクエスト両方にセットします。
     *
     * @param request クライアントからのリクエスト
     * @param response クライアントへのレスポンス
     * @throws ServletException サーブレット内部エラー
     * @throws IOException 入出力例外
     * 【Generated by ChatGPT】
     */
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    	request.setAttribute("isDetailMode", true);
        String idParam = request.getParameter("id");
        if (idParam == null) {
            request.setAttribute("message", "申請IDが不正です。");
            request.getRequestDispatcher("/applicationMain.jsp").forward(request, response);
            return;
        }

        int applicationId = Integer.parseInt(idParam);
        try {
            ApplicationDAO appDao = new ApplicationDAO();
            String type = appDao.getApplicationTypeById(applicationId);
            request.setAttribute("application_id", applicationId);
            request.setAttribute("application_type", type);
            request.setAttribute("mode", "detail");

            if ("出張費".equals(type)) {
                BusinessTripApplicationDAO dao = new BusinessTripApplicationDAO();
                BusinessTripBean bean = dao.loadBusinessTripByApplicationId(applicationId);
                
                request.setAttribute("businessTripBean", bean); // dùng cho confirm.jsp
                request.getSession().setAttribute("businessTripBean", bean); // dùng cho JSP step1/2/3
                
                request.setAttribute("isDetailMode", true);
            }
            // TODO: xử lý cho 交通費 và 立替金 nếu cần

            RequestDispatcher rd = request.getRequestDispatcher("/WEB-INF/views/confirm/applicationConfirm.jsp");
            rd.forward(request, response);

        } catch (Exception e) {
            e.printStackTrace();
            request.setAttribute("message", "詳細情報の取得中にエラーが発生しました。");
            request.getRequestDispatcher("/applicationMain.jsp").forward(request, response);
        }
    }
}