package servlet;

import java.io.IOException;
import java.util.List;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import dao.ApplicationDAO;
import model.Application;

/**
 * 承認者向けに申請一覧を表示するサーブレット。
 * 承認対象の申請情報を取得し、一覧画面に表示する。
 * 【Generated by ChatGPT】
 */
@WebServlet("/approverApplications")
public class ApprovalMainServlet extends HttpServlet {
	/**
	 * 承認者のIDに紐づく申請情報を取得し、申請一覧画面にフォワードする。
	 * 【Generated by ChatGPT】
	 *
	 * @param request  HTTPリクエスト
	 * @param response HTTPレスポンス
	 * @throws ServletException サーブレット例外
	 * @throws IOException      入出力例外
	 */
	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		HttpSession session = request.getSession();
		String approverId = (String) session.getAttribute("staffId");

		try {
			ApplicationDAO dao = new ApplicationDAO();

			String approver_depId = dao.findApproverDepartment(approverId);
			List<Application> applications = dao.getApplicationsByDepartment(approver_depId);
			//            List<Application> applications = dao.getApplicationsByApprover(approverId);
			request.setAttribute("applications", applications);
		} catch (Exception e) {
			e.printStackTrace();
			request.setAttribute("applications", new java.util.ArrayList<Application>());
		}

		request.getRequestDispatcher("/WEB-INF/views/approvalMain.jsp").forward(request, response);
	}

	@Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        String approverId = (String) session.getAttribute("staffId");
        String[] appIds = request.getParameterValues("appIds");  // formでチェックされた申請ID

        if (approverId == null || appIds == null || appIds.length == 0) {
            request.setAttribute("message", "申請が選択されていません。");
            request.getRequestDispatcher("/WEB-INF/views/approvalMain.jsp").forward(request, response);
            return;
        }

        try {
            ApplicationDAO dao = new ApplicationDAO();
            for (String idStr : appIds) {
                int appId = Integer.parseInt(idStr);
                // ステータスを「承認済」へ更新
                dao.updateStatus(appId, approverId);
            }
        }catch (Exception e) {
        	e.printStackTrace();
			// TODO: handle exception
		}
        response.sendRedirect("approverApplications");
        // getで情報を再取得する
    }
}