package servlet;

import java.io.IOException;

import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import dao.PassDao;

/**
 * ユーザーのパスワードを変更するためのサーブレット。
 * 現在のパスワードの確認および新しいパスワードへの更新処理を行う。
 * 【Generated by ChatGPT】
 */
@WebServlet("/changePassword")
public class changepassServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    
    /**
     * GETリクエスト時にはPOSTメソッドに処理を委譲する。
     * 【Generated by ChatGPT】
     *
     * @param request  HTTPリクエスト
     * @param response HTTPレスポンス
     * @throws ServletException サーブレット例外
     * @throws IOException      入出力例外
     */
    protected void doGet(HttpServletRequest request, HttpServletResponse response) 
    	throws ServletException, IOException {
    	
    	doPost(request, response);
    }	
    
    /**
     * パスワード変更処理のメインロジックを実行する。
     * 入力検証・照合・更新処理を含む。
     * 【Generated by ChatGPT】
     *
     * @param request  HTTPリクエスト
     * @param response HTTPレスポンス
     * @throws ServletException サーブレット例外
     * @throws IOException      入出力例外
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {

        // 文字化け防止
        request.setCharacterEncoding("UTF-8");

        // パラメータ取得
        String currentPassword = request.getParameter("currentPassword");
        String newPassword = request.getParameter("newPassword");
        String confirmPassword = request.getParameter("confirmPassword");

        // ログイン中のユーザー情報をセッションから取得
        HttpSession session = request.getSession();
        String staffId = (String) session.getAttribute("staffId");

        if (staffId == null) {
            response.sendRedirect(request.getContextPath() + "/login.jsp");
            return;
        }

        // 現在のパスワードが正しいか確認
        PassDao dao = new PassDao();
        boolean isValid = dao.checkPassword(staffId, currentPassword);

        if (!isValid) {
            request.setAttribute("errorMsg", "現在のパスワードが正しくありません。");
            forwardToForm(request, response);
            return;
        }

        // 新しいパスワードの確認が一致しているか
        if (!newPassword.equals(confirmPassword)) {
            request.setAttribute("errorMsg", "新しいパスワードが一致していません。");
            forwardToForm(request, response);
            return;
        }

        // パスワードを変更する
        boolean updateSuccess = dao.updatePassword(staffId, newPassword);

        if (updateSuccess) {
            // 成功したらホーム画面などへリダイレクト
            response.sendRedirect(request.getContextPath() + "/menu");
            
        } else {
            request.setAttribute("errorMsg", "パスワードの変更に失敗しました。");
            forwardToForm(request, response);
        }
    }

    /**
     * エラーメッセージ付きでパスワード変更フォームへ画面遷移する。
     * 【Generated by ChatGPT】
     *
     * @param request  HTTPリクエスト
     * @param response HTTPレスポンス
     * @throws ServletException サーブレット例外
     * @throws IOException      入出力例外
     */
    private void forwardToForm(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {
        RequestDispatcher dispatcher = request.getRequestDispatcher("/changePass.jsp");
        dispatcher.forward(request, response);
    }
}


//////////////////////////////////////////////ハッシュ
//package servlet;
//
//import java.io.IOException;
//
//import jakarta.servlet.ServletException;
//import jakarta.servlet.annotation.WebServlet;
//import jakarta.servlet.http.HttpServlet;
//import jakarta.servlet.http.HttpServletRequest;
//import jakarta.servlet.http.HttpServletResponse;
//import jakarta.servlet.http.HttpSession;
//
//import bean.Employee;
//import dao.PassDao;
//
//
//@WebServlet("/changePassword")
//public class ChangepassServlet extends HttpServlet {
//    private static final long serialVersionUID = 1L;
//
//    protected void doGet(HttpServletRequest request, HttpServletResponse response)
//            throws ServletException, IOException {
//        doPost(request, response);
//    }
//
//    @Override
//    protected void doPost(HttpServletRequest request, HttpServletResponse response)
//            throws ServletException, IOException {
//
//        request.setCharacterEncoding("UTF-8");
//
//        String currentPassword = request.getParameter("currentPassword");
//        String newPassword = request.getParameter("newPassword");
//        String confirmPassword = request.getParameter("confirmPassword");
//
//        HttpSession session = request.getSession();
//        String staffId = (String) session.getAttribute("staffId");
//
//        if (staffId == null) {
//            response.sendRedirect(request.getContextPath() + "/login.jsp");
//            return;
//        }
//
//        try {
//            String hashedCurrentPass = Employee.hashPassword(currentPassword);
//            PassDao dao = new PassDao();
//            boolean isValid = dao.checkPassword(staffId, hashedCurrentPass);
//
//            if (!isValid) {
//                request.setAttribute("errorMsg", "現在のパスワードが正しくありません。");
//                forwardToForm(request, response);
//                return;
//            }
//
//            if (!newPassword.equals(confirmPassword)) {
//                request.setAttribute("errorMsg", "新しいパスワードが一致していません。");
//                forwardToForm(request, response);
//                return;
//            }
//
//            String hashedNewPass = Employee.hashPassword(newPassword);
//            boolean updateSuccess = dao.updatePassword(staffId, hashedNewPass);
//
//            if (updateSuccess) {
//                response.sendRedirect(request.getContextPath() + "/menu");
//            } else {
//                request.setAttribute("errorMsg", "パスワードの変更に失敗しました。");
//                forwardToForm(request, response);
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//            request.setAttribute("errorMsg", "システムエラーが発生しました。");
//            forwardToForm(request, response);
//        }
//    }
//
//    // 画面遷移用の共通メソッド
//    private void forwardToForm(HttpServletRequest request, HttpServletResponse response)
//            throws ServletException, IOException {
//        request.getRequestDispatcher("/changePass.jsp").forward(request, response);
//    }
//}

