package servlet;

import java.io.IOException;
import java.util.List;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import bean.Employee;
import dao.EmployeeDAO;

/**
 * 社員情報の一覧表示・編集・削除を管理するサーブレット。
 * 編集要求時には対象社員IDをセッションに格納し、登録画面へリダイレクトする。
 * 削除は論理削除として処理され、削除後は社員一覧を再表示する。
 * 【Generated by ChatGPT】
 */
@WebServlet("/employeeControl")
public class EmployeeControlServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * 社員一覧を取得して表示画面にフォワードする。
	 * 【Generated by ChatGPT】
	 *
	 * @param request  HTTPリクエスト
	 * @param response HTTPレスポンス
	 * @throws ServletException サーブレット処理例外
	 * @throws IOException 入出力例外
	 */
	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		EmployeeDAO dao = new EmployeeDAO();
		List<Employee> list = dao.getAllEmployees();

		request.setAttribute("employeeList", list);
		request.getRequestDispatcher("/WEB-INF/views/employeeList.jsp").forward(request, response);
	}

	/**
	 * 編集・削除の各操作に応じた処理を実行する。
	 * 編集時は1名のみ選択可能で、対象IDをセッションに保存する。
	 * 削除時は選択された社員を論理削除する。
	 * 【Generated by ChatGPT】
	 *
	 * @param request  HTTPリクエスト
	 * @param response HTTPレスポンス
	 * @throws ServletException サーブレット処理例外
	 * @throws IOException 入出力例外
	 */
	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		request.setCharacterEncoding("UTF-8");
		String action = request.getParameter("action");
		String[] selectedIds = request.getParameterValues("employeeID");

		if ("edit".equals(action)) {
			if (selectedIds != null && selectedIds.length == 1) {
				HttpSession session = request.getSession();
				session.setAttribute("editEmployeeId", selectedIds[0]);
				response.sendRedirect(request.getContextPath() + "/employeeRegisterPage");
			} else {
				request.setAttribute("errorMsg", "編集する社員を1名選択してください。");
				doGet(request, response);
			}
		} else if ("delete".equals(action)) {
			if (selectedIds != null && selectedIds.length > 0) {
				EmployeeDAO dao = new EmployeeDAO();
				boolean result = true;
				for (String id : selectedIds) {
					// 物理削除 → 論理削除に変更！
					if (!dao.logicalDeleteEmployee(id)) {
						result = false;
					}
				}
				if (result) {
					request.setAttribute("success", "削除が完了しました。");
				} else {
					request.setAttribute("errorMsg", "削除中にエラーが発生しました。");
				}
			} else {
				request.setAttribute("errorMsg", "削除する社員を選択してください。");
			}
			doGet(request, response);
		} else {
			doGet(request, response); 
		}
	}
}
