package servlet;
import java.io.IOException;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

/**
 * ログインユーザーの役職と部署に基づき、適切なメニュー画面（JSP）へ遷移させるルーティングサーブレット。
 * 通常社員、部長（営業部）、管理部のいずれかに応じて画面を切り替える。
 * 【Generated by ChatGPT】
 */
@WebServlet("/menu")
public class MenuRouterServlet extends HttpServlet {
	/**
     * ユーザーの役職と部署情報をセッションから取得し、適切なメニュー画面へフォワードする。
     * デフォルトは staffMenu.jsp。条件により buchouMain.jsp または managerMain.jsp に振り分けられる。
     * 【Generated by ChatGPT】
     *
     * @param req クライアントからのHTTPリクエスト
     * @param res クライアントへのHTTPレスポンス
     * @throws ServletException サーブレットエラー発生時
     * @throws IOException 入出力エラー発生時
     */
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse res)
            throws ServletException, IOException {

        HttpSession session = req.getSession();
        String position = (String) session.getAttribute("position");
        String department = (String) session.getAttribute("department");

        String jspPath = "/WEB-INF/views/staffMenu.jsp"; // default

        if ("部長".equals(position) && "営業部".equals(department)) {
            jspPath = "/WEB-INF/views/buchouMain.jsp";
        } else if ("管理部".equals(department)) {
            jspPath = "/WEB-INF/views/managerMain.jsp";
        }

        req.getRequestDispatcher(jspPath).forward(req, res);
    }
}