package servlet;

import java.io.IOException;
import java.util.List;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import bean.ProjectList;
import dao.ProjectDAO;

// プロジェクト管理表示用
/**
 * プロジェクト管理者用のプロジェクト一覧を表示するためのサーブレット。
 * ProjectDAO を使用して、管理対象のプロジェクト情報を取得し、
 * position.jsp に渡して画面表示を行う。
 * 【Generated by ChatGPT】
 */
@WebServlet("/position_management_view")
public class PositionManagementServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    /**
     * GETリクエストに対して、プロジェクト管理者向けのプロジェクト一覧を取得し、
     * JSP にフォワードして表示する。
     * 【Generated by ChatGPT】
     *
     * @param req  HTTPリクエスト
     * @param resp HTTPレスポンス
     * @throws ServletException サーブレット処理中の例外
     * @throws IOException 入出力エラー発生時
     */
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            ProjectDAO dao = new ProjectDAO();
            List<ProjectList> projectList_management = dao.getAllProject_management();
            req.setAttribute("projectList_management", projectList_management);
            req.getRequestDispatcher("/position.jsp").forward(req, resp);
        } catch (Exception e) {
            throw new ServletException(e);
        }
    }
}