package servlet;

import java.io.IOException;
import java.util.List;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import bean.ProjectList;
import dao.ProjectDAO;

/**
 * プロジェクト管理画面の表示を行うサーブレット。
 * 登録済みプロジェクトの一覧を取得し、JSPに渡して表示する。
 * また、セッションに保存された成功／エラーメッセージを画面に渡す役割も担う。
 * 【Generated by ChatGPT】
 */
@WebServlet("/project_management_view")
public class ProjectManagementServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    /**
     * プロジェクト一覧を取得して画面に表示する。
     * 一覧データの取得後、成功／エラーメッセージがセッションにあればリクエスト属性に渡す。
     * 処理後、JSP（projectList.jsp）へフォワードされる。
     * 【Generated by ChatGPT】
     *
     * @param req  HTTPリクエスト
     * @param resp HTTPレスポンス
     * @throws ServletException サーブレット処理中の例外
     * @throws IOException 入出力エラーが発生した場合
     */
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            ProjectDAO dao = new ProjectDAO();
            List<ProjectList> projectList_management = dao.getAllProject_management();
            req.setAttribute("projectList_management", projectList_management);

            // ここから：セッションからメッセージを取得
            HttpSession session = req.getSession();
        	session.removeAttribute("errorMsg"); // 念のため。次の遷移先にエラー処理がある
            String successMsg = (String) session.getAttribute("successMsg");
            String errorMsg = (String) session.getAttribute("errorMsg");

            if (successMsg != null) {
                req.setAttribute("successMsg", successMsg);
                session.removeAttribute("successMsg");
            }
            if (errorMsg != null) {
                req.setAttribute("errorMsg", errorMsg);
                session.removeAttribute("errorMsg");
            }
            // ここまで

            req.getRequestDispatcher("/WEB-INF/views/projectList.jsp").forward(req, resp);
        } catch (Exception e) {
            throw new ServletException(e);
        }
    }
}
