//package servlet;
//
//import java.io.IOException;
//import java.util.ArrayList;
//import java.util.List;
//
//import jakarta.servlet.ServletException;
//import jakarta.servlet.annotation.MultipartConfig;
//import jakarta.servlet.annotation.WebServlet;
//import jakarta.servlet.http.HttpServlet;
//import jakarta.servlet.http.HttpServletRequest;
//import jakarta.servlet.http.HttpServletResponse;
//import jakarta.servlet.http.HttpSession;
//
//import bean.Project;
//import dao.ProjectDAO;
//
/**
 * 立替金申請（reimbursement）の入力および確認画面への遷移を行うサーブレット。
 * 
 * <p>主な機能:</p>
 * <ul>
 *   <li>GETリクエスト時にはプロジェクト一覧を取得し、申請フォーム画面へ遷移</li>
 *   <li>POSTリクエスト時には入力内容を取得し、確認画面にフォワード</li>
 * </ul>
 *
 * <p>このクラスは @MultipartConfig を使っているが、現状ファイルアップロードは使用していない。</p>
 *
 * 【Generated by ChatGPT】
 */
//@WebServlet("/reimbursement")
//@MultipartConfig
//public class ReimbursementServlet extends HttpServlet {
/**
     * 立替金申請フォーム表示のための処理を行う。
     * プロジェクト一覧を取得し、JSPに渡す。
     *
     * @param request  HTTPリクエスト
     * @param response HTTPレスポンス
     * @throws ServletException サーブレットエラー
     * @throws IOException 入出力エラー
     */
//    @Override
//    protected void doGet(HttpServletRequest request, HttpServletResponse response)
//            throws ServletException, IOException {
//
//        try {
//            List<Project> projectList = new ProjectDAO().getAllProjects();
//            request.setAttribute("projectList", projectList);
//        } catch (Exception e) {
//            e.printStackTrace();
//            request.setAttribute("projectList", new ArrayList<>());
//        }
//
//        request.getRequestDispatcher("/WEB-INF/views/reimbursement.jsp").forward(request, response);
//    }
//
 /**
     * 申請内容を受け取り、確認画面に遷移させる処理を行う。
     * 入力データはリストとしてリクエスト属性に保存され、確認画面に引き継がれる。
     * セッションから staffId を取得し、ログイン確認も実施する。
     *
     * @param request  HTTPリクエスト
     * @param response HTTPレスポンス
     * @throws ServletException サーブレットエラー
     * @throws IOException 入出力エラー
     */
//    @Override
//    protected void doPost(HttpServletRequest request, HttpServletResponse response)
//            throws ServletException, IOException {
//
//        request.setCharacterEncoding("UTF-8");
//        HttpSession session = request.getSession();
//
//        String[] dateList = request.getParameterValues("date[]");
//        String[] destinationsList = request.getParameterValues("destinations[]");
//        String[] projectCodeList = request.getParameterValues("projectCode[]");
//        String[] reportList = request.getParameterValues("report[]");
//        String[] accountingItemList = request.getParameterValues("accountingItem[]");
//        String[] memoList = request.getParameterValues("memo[]");
//        String[] amountList = request.getParameterValues("amount[]");
//
//        String staffId = (String) session.getAttribute("staffId");
//
//        if (staffId == null) {
//            response.sendRedirect(request.getContextPath() + "/login.jsp");
//            return;
//        }
//
//        if (dateList == null || destinationsList == null) {
//            response.sendRedirect(request.getContextPath() + "/reimbursement");
//            return;
//        }
//
//        // Gửi dữ liệu sang màn hình confirm
//        request.setAttribute("dateList", dateList);
//        request.setAttribute("destinationsList", destinationsList);
//        request.setAttribute("projectCodeList", projectCodeList);
//        request.setAttribute("reportList", reportList);
//        request.setAttribute("accountingItemList", accountingItemList);
//        request.setAttribute("memoList", memoList);
//        request.setAttribute("amountList", amountList);
//
//        request.getRequestDispatcher("/WEB-INF/views/confirm/reimbursementConfirm.jsp").forward(request, response);
//    }
//}
