// File: src/main/java/service/BusinessTripInitServlet.java
// (Phiên bản ĐÚNG)
package service;

import java.io.IOException;
import bean.BusinessTripBean;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

@WebServlet("/businessTripInit")
public class BusinessTripInitServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    /**
     * 出張申請の初期画面（Step1）を表示するためのGET処理。
     * <p>
     * ・BusinessTripBean を新規作成しセッションに格納<br>
     * ・プロジェクト一覧をDBから取得しリクエストに設定<br>
     * ・入力画面 (businessTrip1.jsp) へフォワード
     *
     * @param request  クライアントからのリクエスト
     * @param response クライアントへのレスポンス
     * @throws ServletException サーブレット関連の例外
     * @throws IOException 入出力エラー
     * 【Generated by ChatGPT】
     */
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        HttpSession session = request.getSession();
        
        // 1. Tạo một BusinessTripBean mới, rỗng
        BusinessTripBean trip = new BusinessTripBean();
        
        // 2. Lưu bean vào session
        session.setAttribute("trip", trip);

        // 3. DÙNG REDIRECT để yêu cầu trình duyệt gọi đến /businessTripStep1
        // Thao tác này sẽ kích hoạt method doGet của BusinessTripStep1Servlet
        response.sendRedirect(request.getContextPath() + "/businessTripStep1");
    }
}