package service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import bean.BusinessTripBean;
import bean.Step2Detail;
import bean.Step3Detail;
import bean.UploadedFile;
import dao.AllowanceDetailDAO;
import dao.ApplicationDAO;
import dao.BusinessTripApplicationDAO;
import dao.BusinessTripTransportationDetailDAO;
import dao.ReceiptDAO;
import util.DBConnection;

/**
 * 出張申請の提出処理を行うサーブレット。
 * 入力されたデータをデータベースに登録し、添付ファイルを移動する。
 * 
 * 【Generated by ChatGPT】
 */
@WebServlet("/businessTripSubmit")
public class BusinessTripSubmitServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    private static final String PERMANENT_UPLOAD_DIR = "/uploads";

    /**
     * 出張申請データをDBに登録し、申請完了画面へ遷移する。
     * セッション内の出張申請Bean（trip）を用いて、申請ヘッダ・明細・添付ファイル情報を
     * トランザクションとして一括登録する。
     * 
     * @param request  HTTPリクエスト（申請データを含む）
     * @param response HTTPレスポンス（完了／エラー画面への遷移）
     * @throws ServletException サーブレットエラー
     * @throws IOException 入出力エラー
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        HttpSession session = request.getSession(false);
        if (session == null || session.getAttribute("trip") == null) {
            response.sendRedirect(request.getContextPath() + "/businessTripInit");
            return;
        }

        BusinessTripBean trip = (BusinessTripBean) session.getAttribute("trip");
        String staffId = (String) session.getAttribute("staffId");
        Connection conn = null;

        try {
            conn = DBConnection.getConnection();
            conn.setAutoCommit(false); 

            ApplicationDAO appDAO = new ApplicationDAO();
            BusinessTripApplicationDAO tripAppDAO = new BusinessTripApplicationDAO();
            AllowanceDetailDAO allowanceDAO = new AllowanceDetailDAO();
            BusinessTripTransportationDetailDAO transportDAO = new BusinessTripTransportationDetailDAO();
            ReceiptDAO receiptDAO = new ReceiptDAO();

            trip.calculateTotalAmount();

            int applicationId = appDAO.insertApplication("出張費申請", staffId, trip.getTotalAmount(), conn);
            
//            String approverId = appDAO.findManagerId(staffId);
//            if (approverId == null) {
//                throw new Exception("Không tìm thấy người duyệt đơn (部長).");
//            }
//            // ★★★ Dòng này gọi hàm setApprover với 3 tham số, bao gồm `conn`
//            appDAO.setApprover(applicationId, approverId, conn);

            int tripApplicationId = tripAppDAO.insert(trip.getStep1Data(), applicationId, conn);

            // Xử lý Step 2
            for (Step2Detail detail : trip.getStep2Details()) {
                int blockId = allowanceDAO.insert(detail, tripApplicationId, conn);
                List<UploadedFile> filesForBlock = detail.getTemporaryFiles();
                for (int i = 0; i < filesForBlock.size(); i++) {
                    UploadedFile tempFile = filesForBlock.get(i);
                    moveFileToFinalLocation(tempFile, request);
                    receiptDAO.insert(applicationId, "allowance_detail", blockId, i, tempFile, staffId, conn);
                }
            }
            
            // Xử lý Step 3
            for (Step3Detail detail : trip.getStep3Details()) {
                int blockId = transportDAO.insert(detail, tripApplicationId, conn);
                List<UploadedFile> filesForBlock = detail.getTemporaryFiles();
                for (int i = 0; i < filesForBlock.size(); i++) {
                    UploadedFile tempFile = filesForBlock.get(i);
                    moveFileToFinalLocation(tempFile, request);
                    receiptDAO.insert(applicationId, "business_trip_transportation_detail", blockId, i, tempFile, staffId, conn);
                }
            }

            conn.commit(); 
            
            session.removeAttribute("trip");

            request.setAttribute("applicationId", applicationId);
            RequestDispatcher dispatcher = request.getRequestDispatcher("/WEB-INF/views/submitSuccess.jsp");
            dispatcher.forward(request, response);

        } catch (Exception e) {
            e.printStackTrace();
            if (conn != null) { try { conn.rollback(); } catch (SQLException ex) { ex.printStackTrace(); } }
            
            request.setAttribute("errorMessage", "Lỗi nghiêm trọng khi nộp đơn: " + e.getMessage());
            request.getRequestDispatcher("/WEB-INF/views/error.jsp").forward(request, response);
        } finally {
            if (conn != null) { try { conn.close(); } catch (SQLException e) { e.printStackTrace(); } }
        }
    }

    /**
     * 一時フォルダに保存されているファイルを、最終保存フォルダ（/uploads）に移動する。
     * ファイルが存在しない場合はスキップされる。
     * 
     * @param tempFile 一時保存中のファイル情報（パス・ファイル名など）
     * @param request  リクエスト情報（realPath取得用）
     * @throws IOException ファイル操作中のエラー
     */
    private void moveFileToFinalLocation(UploadedFile tempFile, HttpServletRequest request) throws IOException {
        String realPath = request.getServletContext().getRealPath("");
        Path source = Paths.get(realPath + tempFile.getTemporaryPath());
        
        if (Files.exists(source)) {
            Path destinationDir = Paths.get(realPath + PERMANENT_UPLOAD_DIR);
            if (!Files.exists(destinationDir)) {
                Files.createDirectories(destinationDir);
            }
            Path destination = destinationDir.resolve(tempFile.getUniqueStoredName());
            Files.move(source, destination, StandardCopyOption.REPLACE_EXISTING);
            tempFile.setTemporaryPath(PERMANENT_UPLOAD_DIR + "/" + tempFile.getUniqueStoredName());
        }
    }
}